### ISSUE TITLE
helloworld doesn't work on csharp 

### ISSUE THREAD

**Issue by muler415** [rticommunity/rticonnextdds-getting-started#59]
on windows 11,
> cd 2_hello_world
> rtiddsgen -language c# -example net6 -d csharp -ppDisable hello_world.idl
open hello_world.csproj by vs2019
run instance with --pub
I got exception when run 
        using DomainParticipant participant = DomainParticipantFactory.Instance.CreateParticipant(domainId);

Omg.Dds.Core.DdsException
  HResult=0x80131500
  Message=DDS operation failed: 
  Source=Rti.ConnextDds
  StackTrace:
   at Rti.Dds.NativeInterface.Helpers.ReturnCode.CheckResult(IntPtr result)
   at Rti.Dds.NativeInterface.Domain.NativeDomainParticipant.CreateNative(Int32 domainId, DDS_DomainParticipantQos& nativeQos, Object managedParticipant, Boolean enable)
   at Rti.Dds.NativeInterface.Domain.NativeDomainParticipant..ctor(Int32 domainId, Object managedParticipant, Boolean enable)
   at Rti.Dds.Domain.DomainParticipant..ctor(Int32 domainId, Boolean enable)
   at Rti.Dds.Domain.DomainParticipantFactory.CreateParticipant(Int32 domainId)
   at HelloWorldPublisher.RunPublisher(Int32 domainId, Int32 sampleCount) in D:\fengchen\repo\rticonnextdds-getting-started\2_hello_world\csharp\hello_worldPublisher.cs:line 37
   at HelloWorldProgram.Main(String[] args) in D:\fengchen\repo\rticonnextdds-getting-started\2_hello_world\csharp\hello_worldProgram.cs:line 34

please help me out

**Comment by Alxe** [comment]
Hello @muler415, I believe that this is because you don't have a License or haven't configured it properly. Please, take a look at [this Knowledge Base article](https://community.rti.com/kb/why-do-i-get-error-rti-data-distribution-service-no-source-license-information). If you don't have a license, please consider checking [a RTI Connext Trial](https://www.rti.com/free-trial/).

**Comment by muler415** [comment]
Hi, Alejandro,

It works by following the step in knowledge base with evaluation license. It would be better to update help documentation.

Thanks
Forrest

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月23日 17:01
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [rticommunity/rticonnextdds-getting-started] helloworld doesn't work on csharp (Issue #59)


Hello @muler415<https://github.com/muler415>, I believe that this is because you don't have a License or haven't configured it properly. Please, take a look at this Knowledge Base article<https://community.rti.com/kb/why-do-i-get-error-rti-data-distribution-service-no-source-license-information>. If you don't have a license, please consider checking a RTI Connext Trial<https://www.rti.com/free-trial/>.

―
